server.port=8080
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
signature-check.trust-store.path=${SIGNATURE_CHECK_TRUST_STORE_PATH:}
signature-check.trust-store.type=${SIGNATURE_CHECK_TRUST_STORE_TYPE:PKCS12}
signature-check.trust-store.password=${SIGNATURE_CHECK_TRUST_STORE_PASSWORD:}
signature-check.adjunct-store.path=${SIGNATURE_CHECK_ADJUNCT_STORE_PATH:}
signature-check.adjunct-store.type=${SIGNATURE_CHECK_ADJUNCT_STORE_TYPE:PKCS12}
signature-check.adjunct-store.password=${SIGNATURE_CHECK_ADJUNCT_STORE_PASSWORD:}
signature-check.revocation.ocsp-enabled=${SIGNATURE_CHECK_REVOCATION_OCSP_ENABLED:true}
signature-check.revocation.crl-enabled=${SIGNATURE_CHECK_REVOCATION_CRL_ENABLED:true}
signature-check.revocation.fallback-enabled=${SIGNATURE_CHECK_REVOCATION_FALLBACK_ENABLED:true}
signature-check.revocation.cache-enabled=${SIGNATURE_CHECK_REVOCATION_CACHE_ENABLED:true}
signature-check.revocation.cache-directory=${SIGNATURE_CHECK_REVOCATION_CACHE_DIRECTORY:/tmp/dss-revocation-cache}
signature-check.revocation.check-revocation-for-untrusted-chains=${SIGNATURE_CHECK_REVOCATION_CHECK_UNTRUSTED_CHAINS:false}
signature-check.revocation.timeout-connection-millis=${SIGNATURE_CHECK_REVOCATION_TIMEOUT_CONNECTION_MILLIS:3000}
signature-check.revocation.timeout-connection-request-millis=${SIGNATURE_CHECK_REVOCATION_TIMEOUT_CONNECTION_REQUEST_MILLIS:3000}
signature-check.revocation.timeout-response-millis=${SIGNATURE_CHECK_REVOCATION_TIMEOUT_RESPONSE_MILLIS:5000}
signature-check.revocation.timeout-socket-millis=${SIGNATURE_CHECK_REVOCATION_TIMEOUT_SOCKET_MILLIS:5000}
